import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebarsIgo can be generated from the filesystem, or explicitly defined here.
 */
const sidebars: SidebarsConfig = {
  mahjongSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;